<a href="https://colab.research.google.com/github/PrakharPatni08/Gen-AI/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Backpropagation->
Backpropagation is a learning algorithm that allow a neural network to learn by adjusting weights based on the error

Steps:
1. Forward pass(take the input, weight and bias calculate)


In [106]:
import tensorflow as tf
import numpy as np
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.metrics import Accuracy
import pandas as pd


In [107]:
# Load the iris data
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer,StandardScaler

In [108]:
iris = load_iris()
x = iris.data
y = iris.target
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [109]:
#use LabelBinarizer
data = LabelBinarizer()
data1 = data.fit_transform(y)

In [110]:
# normalize features
scaler = StandardScaler()
Scaled = scaler.fit_transform(x)

In [111]:
print(Scaled)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [112]:
x_train,x_test,y_train,y_test = train_test_split(Scaled,data1,test_size = 0.2)

In [113]:
x_train.shape

(120, 4)

In [114]:
y_test.shape

(30, 3)

In [128]:
#Deep Learning Model(Without Backpropagation)
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras import regularizers
def model_creation():
  model = Sequential([
      Dense(10,input_shape=(4,),activation='relu',kernel_regularizer=regulizers.l1(0.01)),
      Dense(3,activation='softmax'),
    ])
  model.compile(optimizer=SGD(learning_rate=0.1),loss=("CategoricalCrossentropy"),metrics=['accuracy'])
  return model

In [116]:
model1= model_creation()
pred1 = model1.predict(x_test)
print(pred1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
[[0.52480763 0.1554839  0.3197085 ]
 [0.3362208  0.17967905 0.48410013]
 [0.42860222 0.27554655 0.29585117]
 [0.36542425 0.32134143 0.31323436]
 [0.4953004  0.14883228 0.3558673 ]
 [0.4188587  0.2571178  0.32402351]
 [0.38661602 0.4260955  0.18728839]
 [0.38304392 0.18550254 0.43145362]
 [0.38895905 0.33007973 0.2809613 ]
 [0.34751067 0.4861133  0.16637605]
 [0.3868047  0.46687716 0.14631814]
 [0.3334453  0.37063792 0.29591674]
 [0.25830022 0.59713167 0.14456812]
 [0.25562876 0.6384422  0.10592892]
 [0.31731415 0.40802294 0.2746629 ]
 [0.32018885 0.14745276 0.5323584 ]
 [0.34473744 0.43389004 0.2213724 ]
 [0.6409093  0.14831613 0.21077451]
 [0.36213297 0.43872535 0.19914168]
 [0.32222876 0.1428398  0.5349314 ]
 [0.40289932 0.17637877 0.42072195]
 [0.32429567 0.14128365 0.5344208 ]
 [0.37099823 0.5240652  0.10493644]
 [0.40330887 0.30245727 0.2942338 ]
 [0.41488189 0.2888633  0.2962548 ]
 [0.33307785 0.13838972 0.52853245]
 [0.28624645 0.12700658 0.

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [117]:
#Model with backpropagation
model2 = model_creation()
model2.fit(x_train,y_train,epochs=100)
pred2 = model2.predict(x_test)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.3433 - loss: 1.1876 
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6298 - loss: 0.8667
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6679 - loss: 0.7269
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7142 - loss: 0.6909 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7542 - loss: 0.6011
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7481 - loss: 0.5718 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7600 - loss: 0.5462
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7967 - loss: 0.4894 
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7792 - loss: 0.4922 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8044 - loss: 0.4549 
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8148 - loss: 0.4285 
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8231 - l

In [119]:
#With Backpropagation
loss,acc = model2.evaluate(x_test,y_test)
print("Accuracy is--> ",acc,"Loss is -->",loss)
#Without Backpropagation
loss1,acc1 = model1.evaluate(x_test,y_test)
print("Accuracy is--> ",acc1,"Loss is --> ",loss1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9667 - loss: 0.0893
Accuracy is-->  0.9666666388511658 Loss is --> 0.08926929533481598
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.2333 - loss: 1.2125
Accuracy is-->  0.23333333432674408 Loss is -->  1.2125492095947266


#Imp Questions and points
1. What is Deep learning?
2. Regularization adds a loss penalty to the model to prevent the model from being overfitten or from being complex
3. what is filter in cnn?
4. what is LSTM?
5. What is optimizer, backpropagation, regularization and its techniques?
6. what is overfitting, and how to avoid it?
7. what is underfitting, and how to avoid it?
8. what is neurons?
9. what is flatten ,dense layer?
10. what is activation fuction and what is relu ,tanh,softmax,sigmoid?
11. what is CNN ? how we can import and resuse
12. What is dropout? how we can use dropout?
13. What is pixel(10,20-28,784)?
14. Why do we need backpropagation in optimizer?
15. deep learning layers (feed forward)