<a href="https://colab.research.google.com/github/PrakharPatni08/Gen-AI/blob/main/NLP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Topic(NLP):-
1. Tokeniztion
2. Embeddings(Word2Vec, Glove)
3. Bag-of-Words and TF-IDF
4. Attention Mechanism
5. Transformer Architecture


# Attention Mechanism:-
Attention is a technique that allows a model to focus on specific words(in a sentence when performing a task)

Why we need Attention??

Attention lets the model attend to all parts of the sequence even for a part of word

Type of Attention
1. Self Attention
2. Global Attention
3. Local Attention
4. Multi-head Attention(we generally use this by creating differents layers)

# Self Attention:-
Q-

K- What each word effect

V-The word representaion


In [ ]:
!pip install torch

In [ ]:
#import imp libraries
import torch
import torch.nn as nn
import torch.functional as fn

In [ ]:
text = ["The","Man","Walk"]

e_d = 8

In [ ]:
wor_to_idx = {i:index for index,i in enumerate(text)}
print(wor_to_idx)

{'The': 0, 'Man': 1, 'Walk': 2}


In [ ]:
idx_to_wor = torch.tensor([wor_to_idx[i] for i in text])
print(idx_to_wor)

tensor([0, 1, 2])


In [ ]:
#Create Embeddings
embedding = nn.Embedding(num_embeddings=len(wor_to_idx),embedding_dim=e_d)

In [ ]:
embeded = embedding(idx_to_wor)

In [ ]:
embeded = embeded.unsqueeze(0)
print(embeded)

tensor([[[-2.5539,  0.1809, -0.0506, -1.4260, -0.5434,  0.5640,  0.2569,
           3.1843],
         [-0.0187, -0.7345, -0.5684,  0.5810,  0.8992,  1.5609,  0.5232,
          -0.1631],
         [ 0.7423,  2.0302,  0.4327,  0.4340,  1.5537, -0.7219, -0.7162,
           0.1250]]], grad_fn=<UnsqueezeBackward0>)


In [ ]:
num_head = 2
multi_head = nn.MultiheadAttention(embed_dim=e_d,num_heads=num_head,batch_first=True)
multi_head

MultiheadAttention(
  (out_proj): NonDynamicallyQuantizableLinear(in_features=8, out_features=8, bias=True)
)

In [ ]:
a_output, a_weights = multi_head(embeded,embeded,embeded)

In [ ]:
a_output

tensor([[[ 0.2458, -0.2673, -0.4076, -0.1714, -0.0884, -0.2016,  0.2529,
          -0.2823],
         [-0.0067, -0.0585, -0.1169, -0.1029, -0.1953, -0.1630,  0.1746,
           0.0253],
         [-0.1679, -0.3407, -0.0121, -0.0587, -0.1625, -0.1971,  0.1999,
           0.0492]]], grad_fn=<TransposeBackward0>)

In [ ]:
a_weights

tensor([[[0.3669, 0.1968, 0.4363],
         [0.2079, 0.3674, 0.4247],
         [0.3303, 0.3317, 0.3380]]], grad_fn=<MeanBackward1>)

In [ ]:
a_weights.squeeze(0).detach().numpy()

array([[0.3668988 , 0.19678602, 0.43631512],
       [0.20790541, 0.36741748, 0.42467713],
       [0.33029765, 0.33169723, 0.33800516]], dtype=float32)

In [ ]:
a_weights

In [ ]:
pip install transformers

In [ ]:
import torch
from transformers import MarianTokenizer, MarianMTModel
model = "Helsinki-NLP/opus-mt-en-hi"
tok = MarianTokenizer.from_pretrained(model)
models = MarianMTModel.from_pretrained(model)

input_txt = ["the man work"]

tok_input = tok(input_txt,return_tensors="pt",padding=True,truncation=True)

In [ ]:
translate = models.generate(**tok_input)

In [ ]:
translate

tensor([[61949,  1026,   182,   161,     5,     0]])

In [ ]:
#Decode
output = tok.batch_decode(translate,skip_special_tokens=True)
print(output)

['आदमी काम करता है']


1. numpy
2. pandas
3. matplotlib
4. seaborn
5. scipy
6. sklearn

7. pytorch
8. tensorflow
9. keras

10. nltk
11. transformers(huggingface)
12. langDetect
13. gensim
14. OpenCV
15. pillow
16. torch vision
17. fast ai(high level deep learning)

CNN Task:-
Face Mask detection usinng cnn and OpenCV